---
id: 
secret: 
modules:
  crud:
    mongo:
      conn: mongodb://localhost:27017
      isPrimary: true
      collections:
        messages:
          isRealtimeEnabled: true
          rules:
            create:
              rule: allow
            read:
              rule: authenticated
            update:
              rule: allow
            delete:
              rule: allow
        users:
          isRealtimeEnabled: true
          rules:
            create:
              rule: allow
            read:
              rule: authenticated
            update:
              rule: allow
            delete:
              rule: allow
        chats:
          isRealtimeEnabled: true
          rules:
            create:
              rule: allow
            read:
              rule: authenticated
            update:
              rule: allow
            delete:
              rule: allow
  auth:
    email:
      enabled: true
  faas:
    enabled: false
    nats: nats://localhost:4222
  realtime:
    enabled: true
    kafka: localhost
  fileStore:
    enabled: false
    storeType: local
    conn: ./
    rules:
      rule1:
        prefix: /
        rule:
          create:
            rule: allow
          read:
            rule: allow
          delete:
            rule: allow